spring:
  profiles:
    active: prod

app:
  cors:
    allowed-origins: "http://localhost:5173"

api:
  seoul:
    base-url: "http://openapi.seoul.go.kr:8088"

---
spring:
  config:
    activate:
      on-profile: local
    import: "optional:classpath:/secret/application-secret.yml"
  datasource:
    url: jdbc:postgresql://localhost:5432/eventdb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

---
spring:
  config:
    activate:
      on-profile: prod
    import: "optional:classpath:/secret/application-secret.yml"
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
