# 📂 src/main/resources/application.yml
spring:
  profiles:
    active: prod # 로컬에서는 H2(local)를, EC2에서는 prod를 씁니다.

---
spring:
  config:
    activate:
      on-profile: local
    import: "optional:classpath:/secret/application-secret.yml" # 💡 앞으로 2칸 뺐습니다!
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: create-drop
---
spring:
  config:
    activate:
      on-profile: prod # EC2 운영 환경 세팅
    import: "optional:classpath:/secret/application-secret.yml" # 💡 앞으로 2칸 뺐습니다!
  jpa:
    hibernate:
      ddl-auto: update # 🚨 운영 환경의 데이터 보호를 위해 반드시 update로 변경!