name: Spring Boot CI/CD to EC2

on:
  push:
    branches: [ "master" ]

env:
  AWS_REGION: ap-northeast-2
  S3_BUCKET_NAME: event-notification-build-bucket # 곧 AWS에서 만들 버킷 이름
  CODE_DEPLOY_APPLICATION_NAME: event-notification-deploy
  CODE_DEPLOY_DEPLOYMENT_GROUP_NAME: event-notification-group

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      # 1. 빌드 파일 압축
      - name: Make zip file
        run: zip -r ./practice-deploy.zip .
      
      # 2. AWS 인증 (GitHub Secrets에 미리 키를 등록해야 함)
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # 3. S3에 업로드
      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./practice-deploy.zip s3://$S3_BUCKET_NAME/practice-deploy.zip

      # 4. CodeDeploy 배포 요청
      - name: Code Deploy
        run: |
          aws deploy create-deployment \
          --application-name ${{ env.CODE_DEPLOY_APPLICATION_NAME }} \
          --deployment-config-name CodeDeployDefault.AllAtOnce \
          --deployment-group-name ${{ env.CODE_DEPLOY_DEPLOYMENT_GROUP_NAME }} \
          --s3-location bucket=$S3_BUCKET_NAME,bundleType=zip,key=practice-deploy.zip